### ISSUE TITLE
problem with R_SH_REL32 relocations for SH

### ISSUE THREAD

**Issue by wafgo** [m-labs/elf2flt-lm32#1]
I'm trying to get ucLinux running on a custom board with an SH2A (Renesas SH7264). With my toochain (build from sources) i can build _u-boot_ and the _kernel_ without any problems. But the kernel flat loader cannot relocate the generated flat binary because of the _R_SH_REL32_ relocation entries. I use the following tools.

**binutils-2.24**
**gcc-4.7.3** _(Configured with: ../gcc-4.7.3/configure --target=sh-linux-uclibc --prefix=/home/devel/cross --disable-nls --disable-multilib -with-cpu=sh2a --enable-languages=c,c++ --enable-initfini-array --without-headers --with-endian=big --disable-shared)_
**uClibc-0.9.33**
**u-boot-2015.07**
**linux-3.17.2**
**elf2flt-lm32-master**(Version ?)

I have a patch for this issue. After applying this patch i can generate a simple initramfs, and everthing looks good. The problem seems to be that the R_SH_REL32 is pc-relative. So I think we dont need to put this entries in the flat relocation section at all when linking with **-emit-relocs**. But i am not sure about this. And i am also not sure how to handle all the other possible SH relocation types. I would like to commit this patch but i don't know how. I would appreciate your help how to commit the patch the right way.

**Comment by mwalle** [comment]
This is the repository for the Lattice Mico32 port of elf2flt. Please report this to the upstream repository, I can't help you.
